<?php
bolt_decrypt( __FILE__ , 'lmQyJC'); return 0;
##!!!##PTo9Op6RnZWjoJGTlVBxoKBrPTo9OqWjlVB5nJylnZmekaSVjHSRpJGSkaOVjHWcn6GllZ6kjHaRk6SfopmVo4x4kaN2kZOkn6Kpaz06paOVUHmcnKWdmZ6RpJWMdJGkkZKRo5WMdZyfoaWVnqSMfZ+UlZxrPTo9OpOckaOjUJmjo6WVdpmVnJSjlaR3op+loFCVqKSVnpSjUH2flJWcPTqrPTpQUFBQpaOVUHiRo3aRk6SfoqlrPTo9OlBQUFCgop+klZOklZRQVJelkaKUlZRQbVCLV5mUV41rPTqtPTo=